# Generated by Django 4.2.7 on 2023-11-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('commoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course.commoninfo')),
                ('expenses', models.IntegerField()),
                ('superuser', models.BooleanField()),
            ],
            bases=('course.commoninfo',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('commoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='course.commoninfo')),
                ('salary', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            bases=('course.commoninfo',),
        ),
    ]
