# Generated by Django 4.2.7 on 2023-11-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_commoninfo_principal_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principal',
            name='commoninfo_ptr',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='commoninfo_ptr',
        ),
        migrations.DeleteModel(
            name='CommonInfo',
        ),
        migrations.DeleteModel(
            name='Principal',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
