# Generated by Django 4.2.7 on 2023-11-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_principal_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Principal',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
