# Generated by Django 4.2.7 on 2023-12-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_page_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('desc', models.TextField(max_length=70)),
                ('publish_date', models.IntegerField()),
            ],
        ),
    ]
