# Generated by Django 4.2.7 on 2023-12-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_pagination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagination',
            name='desc',
            field=models.TextField(max_length=700),
        ),
    ]
