# Generated by Django 4.2.7 on 2023-12-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_pagination_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagination',
            name='publish_date',
            field=models.DateTimeField(),
        ),
    ]
